name: Staging build

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run SSH commands
        # Documentation: https://github.com/marketplace/actions/ssh-remote-commands
        uses: appleboy/ssh-action@master
        env:
          NODE_PORT: 3001
          MAPBOX_API_KEY: pk.eyJ1IjoidG5jc29pbHNjaWVuY2UiLCJhIjoiY2s5Y3dweXg0MDBlZjNkbXE5ZGk4Y294biJ9.nGYVoUKe7Z8MJoi5GwCGjg
          API_URL: http://35.233.41.65/user/skydipper/api/v2
          ANALYSIS_API_URL: https://soilsrevealed.org/api/v1/analysis
          GEE_KEY: ${{ secrets.GEE_KEY }}
          GOOGLE_ANALYTICS_KEY:
          TILES_URL: https://soils-revealed.s3.amazonaws.com/tiles
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          envs: NODE_PORT,MAPBOX_API_KEY,API_URL,ANALYSIS_API_URL,GEE_KEY,GOOGLE_ANALYTICS_KEY,TILES_URL
          script: |
            echo '> Source nvm'
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            echo '> Export the path'
            export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v12.16.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
            echo '> Kill previous node server'
            pm2 stop staging
            echo '> Open staging folder'
            cd ~/soils-revealed-staging
            echo '> Pull from git'
            git fetch origin develop
            git reset --hard origin/develop
            echo '> Use correct node version'
            nvm install
            nvm use
            echo '> Install dependencies'
            yarn install --frozen-lockfile
            echo '> Generate a deployment key'
            DEPLOYMENT_KEY=`date +%s`
            echo '> Create .env file'
            echo -e "PORT=$NODE_PORT\nMAPBOX_API_KEY=$MAPBOX_API_KEY\nAPI_URL=$API_URL\nANALYSIS_API_URL=$ANALYSIS_API_URL\nDEPLOYMENT_KEY=$DEPLOYMENT_KEY\nGOOGLE_ANALYTICS_KEY=$GOOGLE_ANALYTICS_KEY\nTILES_URL=$TILES_URL" > .env
            echo '> Create gee.key.json file'
            echo $GEE_KEY > gee.key.json
            echo '> Build the app'
            yarn build
            echo '> Run the server'
            pm2 start staging
