name: Staging build

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run SSH commands
        # Documentation: https://github.com/marketplace/actions/ssh-remote-commands
        uses: appleboy/ssh-action@master
        env:
          PORT: 3001
          MAPBOX_API_KEY: pk.eyJ1IjoidG5jc29pbHNjaWVuY2UiLCJhIjoiY2s5Y3dweXg0MDBlZjNkbXE5ZGk4Y294biJ9.nGYVoUKe7Z8MJoi5GwCGjg
        with:
          debug: true
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: PORT,MAPBOX_API_KEY
          script: |
            echo '> Kill previous node server'
            pm2 stop staging
            echo '> Open staging folder'
            cd ~/soils-revealed-staging
            echo '> Pull from git'
            git pull
            echo '> Use correct node version'
            nvm install
            nvm use
            echo '> Install dependencies'
            yarn install --frozen-lockfile
            echo '> Create .env file'
            echo "PORT=$PORT\nMAPBOX_API_KEY=$MAPBOX_API_KEY" > .env
            echo '> Build the app'
            yarn build
            echo '> Run the server'
            pm2 start staging
